/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Administrator
 */
public class Datechooser extends javax.swing.JPanel {
    Connection conn;
    /**
     * Creates new form Datechooser
     */
    public Datechooser() {
        initComponents();
         txtDate.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateDate();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateDate();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateDate();
            }

            private void updateDate() {
//                try {
//                    String inputText = txtDate.getText();
//                    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMMM-yyyy");
//                    Date inputDate = dateFormat.parse(inputText);
//                    
//                    // Menambahkan 30 hari ke tanggal input
//                    Calendar calendar = Calendar.getInstance();
//                    calendar.setTime(inputDate);
//                    calendar.add(Calendar.DAY_OF_MONTH, 30);
//                    Date newDate = calendar.getTime();
//                    
//                    // Menampilkan tanggal baru di jTextField2
//                    txtDate2.setText(dateFormat.format(newDate));
//                } catch (Exception ex) {
//                    txtDate2.setText("Invalid Date");
//                }
//            }
                 try {
            String inputText = txtDate.getText();
            String multiplierText = txtDate3.getText();
            int multiplier = Integer.parseInt(multiplierText);

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMMM-yyyy");
            Date inputDate = dateFormat.parse(inputText);
            
            // Mengalikan jumlah hari dengan nilai dari txtDate3
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(inputDate);
            calendar.add(Calendar.DAY_OF_MONTH, multiplier * 30);
            Date newDate = calendar.getTime();
            
            // Menampilkan tanggal baru di txtDate2
            txtDate2.setText(dateFormat.format(newDate));
        } catch (Exception ex) {
            txtDate2.setText("Invalid Date");
        }
    }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new com.raven.datechooser.DateChooser();
        txtDate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtDate2 = new javax.swing.JTextField();
        txtDate3 = new javax.swing.JTextField();

        date.setDateFormat("dd-MMMM-yyyy");
        date.setTextRefernce(txtDate);

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        txtDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/calendar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtDate2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtDate3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtDate2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDate3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDate3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
    date.toDay();        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.datechooser.DateChooser date;
    private javax.swing.JButton jButton1;
    public javax.swing.JTextField txtDate;
    public javax.swing.JTextField txtDate2;
    public javax.swing.JTextField txtDate3;
    // End of variables declaration//GEN-END:variables
}
