/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.*;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import main.Config;
import swing.ScrollBar;

/**
 *
 * @author Administrator
 */
public class Form_RiwayatTransaksi extends javax.swing.JPanel {

    /**
     * Creates new form Form_RiwayatTransaksi
     */
    public Form_RiwayatTransaksi() {
        initComponents();
        load_table();
        
        JPanel p = new JPanel();
        p.setBackground(Color.white);
        jScrollPane1.setVerticalScrollBar(new ScrollBar());
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        jScrollPane1.setCorner(jScrollPane1.UPPER_RIGHT_CORNER, p); 
        
    }
    
    

        public void load_table(){
            Connection conn;
            PreparedStatement pst;
            ResultSet rs;
            try{
                int q;
                conn = (Connection) Config.configDB();
                String sql = "SELECT * FROM riwayat_tr";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                java.sql.ResultSetMetaData rsmd = rs.getMetaData();
                q = rsmd.getColumnCount();
                DefaultTableModel model = (DefaultTableModel) tabel2.getModel();
                model.setColumnIdentifiers(new Object[]{"Tanggal", "No Kamar", "Nama Penyewa", "Tgl Mulai", "Tgl Akhir", "Jml Bulan", "Total Harga"});
                
                while (rs.next()) {
                Vector<Object> row = new Vector<>();
                for (int i = 1; i <= q; i++) {
                row.add(rs.getString("tanggal"));
                row.add(rs.getString("no_kamar"));
                row.add(rs.getString("nama_penyewa"));
                row.add(rs.getString("tgl_mulai"));
                row.add(rs.getString("tgl_akhir"));
                row.add(rs.getString("jumlah_bulan"));
                row.add(rs.getString("total_harga"));
                }
                model.addRow(row);
            }
             rs.close();
             pst.close();
             
            } catch (Exception e){
             e.printStackTrace();   
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel2 = new swing.Tabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 25)); // NOI18N
        jLabel1.setText("Riwayat Transaksi");

        jScrollPane1.setBorder(null);

        tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabel2.setEnabled(false);
        jScrollPane1.setViewportView(tabel2);

        jButton1.setBackground(new java.awt.Color(255, 195, 215));
        jButton1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(127, 82, 139));
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        load_table();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.Tabel tabel2;
    // End of variables declaration//GEN-END:variables
}
